//Please Note that this was auto-generated by a self-made engine

#pragma once
#include "Model.h"
void GenerateModels(std::vector<Model>& models)
{

Model Sphere0;
Sphere0.CreateSphere(0.5, 14, 14);
Sphere0.Translate(-0.92, -0.25, -0.45);
Sphere0.TranslateAccum(0.8, 0, 2.5);
Sphere0.Scale(0.75, 0.75, 0.75);
Sphere0.group = 0;
models.emplace_back(Sphere0);

Model Sphere1;
Sphere1.CreateSphere(0.5, 22, 10);
Sphere1.Translate(-0.91, 0.3, -0.45);
Sphere1.TranslateAccum(0.8, 0, 2.5);
Sphere1.Scale(0.54, 0.54, 0.54);
Sphere1.group = 0;
models.emplace_back(Sphere1);

Model Cylinder2;
Cylinder2.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder2.Translate(-0.719, 0.384, -0.48);
Cylinder2.TranslateAccum(0.8, 0, 2.5);
Cylinder2.Scale(0.052, 0.052, 1);
Cylinder2.Rotate(85.42, 47.29, 0);
Cylinder2.group = 0;
models.emplace_back(Cylinder2);

Model Cone3;
Cone3.CreateCone(0.5, 0.5, 10, 10);
Cone3.Translate(-0.915, 0.693, -0.49);
Cone3.TranslateAccum(0.8, 0, 2.5);
Cone3.Scale(0.187, 0.187, 0.302);
Cone3.Rotate(0, 180.6, 0);
Cone3.SetColor(0.9804, 0.6949, 0.009612);
Cone3.group = 0;
models.emplace_back(Cone3);

Model Sphere4;
Sphere4.CreateSphere(0.5, 17, 10);
Sphere4.Translate(-0.866, 0.742, -0.52);
Sphere4.TranslateAccum(0.8, 0, 2.5);
Sphere4.Scale(0.116, 0.116, 0.116);
Sphere4.SetColor(0, 0, 0);
Sphere4.group = 0;
models.emplace_back(Sphere4);

Model Cylinder5;
Cylinder5.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder5.Translate(-1.087, 0.435, -0.45);
Cylinder5.TranslateAccum(0.8, 0, 2.5);
Cylinder5.Scale(0.052, 0.052, 1);
Cylinder5.Rotate(85.42, 312.7, 0);
Cylinder5.group = 0;
models.emplace_back(Cylinder5);

Model Torus6;
Torus6.CreateTours(0.1, 0.8, 12, 23);
Torus6.Translate(-0.913, 0.697, -0.55);
Torus6.TranslateAccum(0.8, 0, 2.5);
Torus6.Scale(0.098, 0.098, 0.063);
Torus6.Rotate(227.4, 0, 360);
Torus6.SetColor(0, 0, 0);
Torus6.group = 0;
models.emplace_back(Torus6);

Model CollisionBox7;
CollisionBox7.CreateWireCube(0.5);
CollisionBox7.Translate(-0.911, 0.213, -0.5);
CollisionBox7.TranslateAccum(0.8, 0, 2.5);
CollisionBox7.Scale(1.356, 2.561, 1);
CollisionBox7.collider = true;
CollisionBox7.group = 0;
models.emplace_back(CollisionBox7);

Model Sphere8;
Sphere8.CreateSphere(0.5, 16, 15);
Sphere8.Translate(-0.918, 0.697, -0.45);
Sphere8.TranslateAccum(0.8, 0, 2.5);
Sphere8.Scale(0.302, 0.302, 0.302);
Sphere8.group = 0;
models.emplace_back(Sphere8);

Model Sphere9;
Sphere9.CreateSphere(0.5, 22, 10);
Sphere9.Translate(-0.957, 0.76, -0.53);
Sphere9.TranslateAccum(0.8, 0, 2.5);
Sphere9.Scale(0.09, 0.09, 0.09);
Sphere9.SetColor(0, 0, 0);
Sphere9.group = 0;
models.emplace_back(Sphere9);

Model Cone10;
Cone10.CreateCone(0.5, 0.5, 10, 10);
Cone10.Translate(-0.849, -0.743, 0.912);
Cone10.Scale(0.364, 0.275, 0.623);
Cone10.Rotate(89.2, 175.2, 0);
Cone10.SetColor(0.099, 0.56, 0);
Cone10.group = 1;
models.emplace_back(Cone10);

Model Cone11;
Cone11.CreateCone(0.5, 0.5, 10, 10);
Cone11.Translate(0, -0.743, 0.912);
Cone11.Scale(0.364, 0.275, 0.623);
Cone11.Rotate(89.2, 175.2, 0);
Cone11.SetColor(0.09948, 0.5637, 0);
Cone11.group = 1;
models.emplace_back(Cone11);

Model Cone12;
Cone12.CreateCone(0.5, 0.5, 10, 10);
Cone12.Translate(1.027, -0.778, -0.561);
Cone12.Scale(0.364, 0.275, 0.623);
Cone12.Rotate(89.2, 175.2, 0);
Cone12.SetColor(0.099, 0.56, 0);
Cone12.group = 1;
models.emplace_back(Cone12);

Model Cone13;
Cone13.CreateCone(0.5, 0.5, 10, 10);
Cone13.Translate(-1.38, -0.778, -1.193);
Cone13.Scale(0.364, 0.275, 0.623);
Cone13.Rotate(89.2, 175.2, 0);
Cone13.SetColor(0.099, 0.5637, 0);
Cone13.group = 1;
models.emplace_back(Cone13);

Model Cone14;
Cone14.CreateCone(0.5, 0.5, 10, 10);
Cone14.Translate(1.416, -0.708, 1.579);
Cone14.Scale(0.364, 0.275, 0.623);
Cone14.Rotate(89.2, 175.2, 0);
Cone14.SetColor(0.09948, 0.5637, 0);
Cone14.group = 1;
models.emplace_back(Cone14);

Model Cone15;
Cone15.CreateCone(0.5, 0.5, 10, 10);
Cone15.Translate(0.284, -0.778, -1.298);
Cone15.Scale(0.364, 0.275, 0.623);
Cone15.Rotate(89.2, 175.2, 0);
Cone15.SetColor(0.09948, 0.5637, 0);
Cone15.group = 1;
models.emplace_back(Cone15);

Model Cone16;
Cone16.CreateCone(0.5, 0.5, 10, 10);
Cone16.Translate(-1.38, -0.778, -0.561);
Cone16.Scale(0.364, 0.275, 0.623);
Cone16.Rotate(89.2, 175.2, 0);
Cone16.SetColor(0.09948, 0.5637, 0);
Cone16.group = 1;
models.emplace_back(Cone16);

Model Cone17;
Cone17.CreateCone(0.5, 0.5, 10, 10);
Cone17.Translate(-0.088, -0.708, 0);
Cone17.Scale(0.364, 0.275, 0.623);
Cone17.Rotate(89.2, 175.2, 0);
Cone17.SetColor(0.09948, 0.5637, 0);
Cone17.group = 1;
models.emplace_back(Cone17);

Model Cone18;
Cone18.CreateCone(0.5, 0.5, 10, 10);
Cone18.Translate(-1.38, -0.778, 1.579);
Cone18.Scale(0.364, 0.275, 0.623);
Cone18.Rotate(89.2, 175.2, 0);
Cone18.SetColor(0.09948, 0.5637, 0);
Cone18.group = 1;
models.emplace_back(Cone18);

Model Cube26;
Cube26.CreateCube(0.5);
Cube26.Translate(2.434, 0.243, 0.348);
Cube26.TranslateAccum(-1, 0, 0);
Cube26.Scale(0.095, 4.337, 0.094);
Cube26.group = 3;
models.emplace_back(Cube26);

Model Cube27;
Cube27.CreateCube(0.5);
Cube27.Translate(1.49, 1.458, -0.034);
Cube27.TranslateAccum(-1, 0, 0);
Cube27.Scale(4.408, 0.278, 0.416);
Cube27.SetColor(0.6392, 0.4235, 0);
Cube27.group = 3;
models.emplace_back(Cube27);

Model Cube28;
Cube28.CreateCube(0.5);
Cube28.Translate(2.434, 0.339, -0.449);
Cube28.TranslateAccum(-1, 0, 0);
Cube28.Scale(0.095, 4.337, 0.094);
Cube28.group = 3;
models.emplace_back(Cube28);

Model Cube29;
Cube29.CreateCube(0.5);
Cube29.Translate(1.49, 1.367, 0.191);
Cube29.TranslateAccum(-1, 0, 0);
Cube29.Scale(4.408, 0.278, 0.416);
Cube29.SetColor(0.651, 0.4039, 0);
Cube29.group = 3;
models.emplace_back(Cube29);

Model Cube30;
Cube30.CreateCube(0.5);
Cube30.Translate(0.474, 0.328, -0.449);
Cube30.TranslateAccum(-1, 0, 0);
Cube30.Scale(0.095, 4.337, 0.094);
Cube30.group = 3;
models.emplace_back(Cube30);

Model Cube31;
Cube31.CreateCube(0.5);
Cube31.Translate(1.49, 1.424, -0.247);
Cube31.TranslateAccum(-1, 0, 0);
Cube31.Scale(4.408, 0.278, 0.416);
Cube31.SetColor(0.652, 0.4027, 0);
Cube31.group = 3;
models.emplace_back(Cube31);

Model Cube32;
Cube32.CreateCube(0.5);
Cube32.Translate(1.479, 1.446, -0.449);
Cube32.TranslateAccum(-1, 0, 0);
Cube32.Scale(4.408, 0.278, 0.416);
Cube32.SetColor(0.6431, 0.4235, 0);
Cube32.group = 3;
models.emplace_back(Cube32);

Model Cube33;
Cube33.CreateCube(0.5);
Cube33.Translate(1.49, 1.379, 0.404);
Cube33.TranslateAccum(-1, 0, 0);
Cube33.Scale(4.408, 0.278, 0.416);
Cube33.SetColor(0.6471, 0.4235, 0);
Cube33.group = 3;
models.emplace_back(Cube33);

Model Cube34;
Cube34.CreateCube(0.5);
Cube34.Translate(0.519, 0.243, 0.348);
Cube34.TranslateAccum(-1, 0, 0);
Cube34.Scale(0.095, 4.337, 0.094);
Cube34.group = 3;
models.emplace_back(Cube34);

Model Cylinder35;
Cylinder35.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder35.Translate(0.321, 0.737, -1.132);
Cylinder35.TranslateAccum(-1, 0, 0);
Cylinder35.Scale(0.035, 0.055, 3);
Cylinder35.Rotate(74.3, 0, 4142);
Cylinder35.SetColor(0.4363, 0.4063, 0.4063);
Cylinder35.group = 4;
models.emplace_back(Cylinder35);

Model Cube36;
Cube36.CreateCube(0.5);
Cube36.Translate(-0.202, -0.166, -1.019);
Cube36.Scale(1.034, 0.092, 0.073);
Cube36.Rotate(0, 0, 4142);
Cube36.SetColor(0.8588, 0.4863, 0.2863);
Cube36.group = 4;
models.emplace_back(Cube36);

Model Cube37;
Cube37.CreateCube(0.5);
Cube37.Translate(-0.202, -0.162, -0.972);
Cube37.Scale(1.034, 0.092, 0.073);
Cube37.Rotate(0, 0, 4142);
Cube37.SetColor(0.8588, 0.4863, 0.2863);
Cube37.group = 4;
models.emplace_back(Cube37);

Model Cylinder38;
Cylinder38.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder38.Translate(-0.93, 0.737, -1.132);
Cylinder38.Scale(0.035, 0.055, 3);
Cylinder38.Rotate(74.3, 0, 4142);
Cylinder38.SetColor(0.4755, 0.4242, 0.4242);
Cylinder38.group = 4;
models.emplace_back(Cylinder38);

Model Cube39;
Cube39.CreateCube(0.5);
Cube39.Translate(-0.202, -0.141, -1.103);
Cube39.Scale(1.034, 0.092, 0.073);
Cube39.Rotate(0, 0, 4142);
Cube39.SetColor(0.8588, 0.4863, 0.2863);
Cube39.group = 4;
models.emplace_back(Cube39);

Model Cube40;
Cube40.CreateCube(0.5);
Cube40.Translate(-0.288, 0.721, -1.073);
Cube40.Scale(2.656, 0.175, 0.392);
Cube40.Rotate(0, 0, 4142);
Cube40.SetColor(0.402, 0.1714, 0.1714);
Cube40.group = 4;
models.emplace_back(Cube40);

Model Cylinder41;
Cylinder41.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder41.Translate(0.321, 0.737, -1.12);
Cylinder41.Scale(0.035, 0.055, 3);
Cylinder41.Rotate(93.33, 0, 4142);
Cylinder41.SetColor(0.4275, 0.4196, 0.4196);
Cylinder41.group = 4;
models.emplace_back(Cylinder41);

Model Cylinder42;
Cylinder42.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder42.Translate(-0.926, 0.737, -1.12);
Cylinder42.Scale(0.035, 0.055, 3);
Cylinder42.Rotate(93.33, 0, 4142);
Cylinder42.SetColor(0.4657, 0.4177, 0.4177);
Cylinder42.group = 4;
models.emplace_back(Cylinder42);

Model Cube43;
Cube43.CreateCube(0.5);
Cube43.Translate(-0.45, 0.266, -1.051);
Cube43.Scale(0.01, 1.613, 0.01);
Cube43.Rotate(0, 0, 4142);
Cube43.SetColor(0.4853, 0.4853, 0.4853);
Cube43.group = 4;
models.emplace_back(Cube43);

Model Cube44;
Cube44.CreateCube(0.5);
Cube44.Translate(-0.206, -0.137, -1.056);
Cube44.Scale(1.034, 0.092, 0.073);
Cube44.Rotate(0, 0, 4142);
Cube44.SetColor(0.8588, 0.4863, 0.2863);
Cube44.group = 4;
models.emplace_back(Cube44);

Model Cube45;
Cube45.CreateCube(0.5);
Cube45.Translate(-0.007, 0.27, -1.094);
Cube45.Scale(0.01, 1.829, 0.01);
Cube45.Rotate(0, 0, 4142);
Cube45.SetColor(0.6765, 0.6765, 0.6765);
Cube45.group = 4;
models.emplace_back(Cube45);

Model Cube46;
Cube46.CreateCube(0.5);
Cube46.Translate(-0.202, -0.145, -1.145);
Cube46.Scale(1.034, 0.092, 0.073);
Cube46.Rotate(0, 0, 4142);
Cube46.SetColor(0.8588, 0.4863, 0.2863);
Cube46.group = 4;
models.emplace_back(Cube46);

Model Sphere47;
Sphere47.CreateSphere(0.5, 10, 10);
Sphere47.Translate(-0.652, 0.261, 0.755);
Sphere47.Scale(0.41, 0.41, 0.41);
Sphere47.SetColor(1, 0, 0);
Sphere47.group = 5;
models.emplace_back(Sphere47);

Model Sphere48;
Sphere48.CreateSphere(0.5, 10, 10);
Sphere48.Translate(-0.823, 0.261, 0.755);
Sphere48.Scale(0.41, 0.41, 0.41);
Sphere48.SetColor(0.147, 0, 1);
Sphere48.group = 5;
models.emplace_back(Sphere48);

Model Cone49;
Cone49.CreateCone(0.5, 0.5, 10, 10);
Cone49.Translate(-0.737, 0.304, 0.755);
Cone49.Scale(0.648, 0.576, 2.295);
Cone49.Rotate(95.75, 0, 0);
Cone49.SetColor(1, 0.6786, 0);
Cone49.group = 5;
models.emplace_back(Cone49);

Model Sphere50;
Sphere50.CreateSphere(0.5, 10, 10);
Sphere50.Translate(-0.716, 0.389, 0.585);
Sphere50.Scale(0.41, 0.41, 0.41);
Sphere50.SetColor(1, 0, 0.9118);
Sphere50.group = 5;
models.emplace_back(Sphere50);


Model Cube52;
Cube52.CreateCube(0.5);
Cube52.Translate(-0.287, -0.149, 1.543);
Cube52.Scale(1.933, 0.088, 0.139);
Cube52.Rotate(90, 0, 4142);
Cube52.SetColor(0.6588, 0.4588, 0.2706);
Cube52.group = 6;
models.emplace_back(Cube52);

Model Torus53;
Torus53.CreateTours(0.266, 0.553, 10, 10);
Torus53.Translate(0.224, -0.525, 1.684);
Torus53.Scale(0.183, 0.183, 0.183);
Torus53.Rotate(0, 92.39, 4142);
Torus53.SetColor(0.6235, 0.6235, 0.6314);
Torus53.group = 6;
models.emplace_back(Torus53);

Model Cube54;
Cube54.CreateCube(0.5);
Cube54.Translate(-0.248, -0.483, 1.872);
Cube54.Scale(1.938, 0.088, 0.139);
Cube54.Rotate(31.88, 0, 4142);
Cube54.SetColor(0.6588, 0.4588, 0.2706);
Cube54.group = 6;
models.emplace_back(Cube54);

Model Cylinder55;
Cylinder55.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder55.Translate(0.211, -0.42, 1.584);
Cylinder55.Scale(0.091, 0.091, 0.627);
Cylinder55.Rotate(253.1, 0, 4142);
Cylinder55.SetColor(0.6275, 0.6274, 0.6274);
Cylinder55.group = 6;
models.emplace_back(Cylinder55);

Model Cube56;
Cube56.CreateCube(0.5);
Cube56.Translate(-0.287, -0.399, 1.625);
Cube56.Scale(1.857, 0.088, 0.139);
Cube56.Rotate(20.63, 0, 4142);
Cube56.SetColor(0.6588, 0.4588, 0.2706);
Cube56.group = 6;
models.emplace_back(Cube56);

Model Cylinder57;
Cylinder57.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder57.Translate(-0.747, -0.42, 1.584);
Cylinder57.Scale(0.091, 0.091, 0.627);
Cylinder57.Rotate(253.1, 0, 4142);
Cylinder57.SetColor(0.6275, 0.6274, 0.6274);
Cylinder57.group = 6;
models.emplace_back(Cylinder57);

Model Cylinder58;
Cylinder58.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder58.Translate(0.211, -0.399, 1.872);
Cylinder58.Scale(0.091, 0.091, 0.627);
Cylinder58.Rotate(178.1, 0, 4142);
Cylinder58.SetColor(0.6275, 0.6274, 0.6274);
Cylinder58.group = 6;
models.emplace_back(Cylinder58);

Model Cube59;
Cube59.CreateCube(0.5);
Cube59.Translate(-0.268, -0.441, 1.811);
Cube59.Scale(1.93, 0.088, 0.139);
Cube59.Rotate(208.1, 0, 4142);
Cube59.SetColor(0.6588, 0.4588, 0.2706);
Cube59.group = 6;
models.emplace_back(Cube59);

Model Cube60;
Cube60.CreateCube(0.5);
Cube60.Translate(-0.268, -0.42, 1.749);
Cube60.Scale(2.026, 0.088, 0.139);
Cube60.Rotate(0, 0, 4142);
Cube60.SetColor(0.6569, 0.4637, 0.2705);
Cube60.group = 6;
models.emplace_back(Cube60);

Model Cube61;
Cube61.CreateCube(0.5);
Cube61.Translate(-0.287, -0.358, 1.563);
Cube61.Scale(1.985, 0.088, 0.139);
Cube61.Rotate(71.25, 0, 4142);
Cube61.SetColor(0.6588, 0.4588, 0.2706);
Cube61.group = 6;
models.emplace_back(Cube61);

Model Cylinder62;
Cylinder62.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder62.Translate(0.211, -0.649, 1.976);
Cylinder62.Scale(0.091, 0.091, 0.602);
Cylinder62.Rotate(245.6, 0, 4142);
Cylinder62.SetColor(0.6275, 0.6274, 0.6274);
Cylinder62.group = 6;
models.emplace_back(Cylinder62);

Model Cube63;
Cube63.CreateCube(0.5);
Cube63.Translate(-0.268, -0.42, 1.687);
Cube63.Scale(1.93, 0.088, 0.139);
Cube63.Rotate(0, 0, 4142);
Cube63.SetColor(0.6588, 0.4588, 0.2706);
Cube63.group = 6;
models.emplace_back(Cube63);

Model Cube64;
Cube64.CreateCube(0.5);
Cube64.Translate(-0.287, -0.274, 1.563);
Cube64.Scale(1.985, 0.088, 0.139);
Cube64.Rotate(90, 0, 4142);
Cube64.SetColor(0.6588, 0.4588, 0.2706);
Cube64.group = 6;
models.emplace_back(Cube64);

Model Cylinder65;
Cylinder65.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder65.Translate(-0.747, -0.399, 1.872);
Cylinder65.Scale(0.091, 0.091, 0.627);
Cylinder65.Rotate(178.1, 0, 4142);
Cylinder65.SetColor(0.6275, 0.6274, 0.6274);
Cylinder65.group = 6;
models.emplace_back(Cylinder65);

Model Cylinder66;
Cylinder66.CreateCylinder(0.5, 0.5, 0.5, 10, 10);
Cylinder66.Translate(-0.747, -0.649, 1.976);
Cylinder66.Scale(0.091, 0.091, 0.602);
Cylinder66.Rotate(245.6, 0, 4142);
Cylinder66.SetColor(0.6275, 0.6274, 0.6274);
Cylinder66.group = 6;
models.emplace_back(Cylinder66);

Model Cube67;
Cube67.CreateCube(0.5);
Cube67.Translate(-0.268, -0.232, 1.543);
Cube67.Scale(1.933, 0.088, 0.139);
Cube67.Rotate(90, 0, 4142);
Cube67.SetColor(0.6588, 0.4588, 0.2706);
Cube67.group = 6;
models.emplace_back(Cube67);

Model Torus68;
Torus68.CreateTours(0.266, 0.553, 10, 10);
Torus68.Translate(-0.767, -0.525, 1.684);
Torus68.Scale(0.183, 0.183, 0.183);
Torus68.Rotate(0, 92.39, 4142);
Torus68.SetColor(0.6235, 0.6235, 0.6314);
Torus68.group = 6;
models.emplace_back(Torus68);

Model Cube69;
Cube69.CreateCube(0.5);
Cube69.Translate(-0.287, -0.526, 1.914);
Cube69.Scale(1.85, 0.088, 0.139);
Cube69.Rotate(52.5, 0, 4142);
Cube69.SetColor(0.6588, 0.4588, 0.2706);
Cube69.group = 6;
models.emplace_back(Cube69);

Model Cube70;
Cube70.CreateCube(0.5);
Cube70.Translate(0.071, -0.672, 0.351);
Cube70.Scale(10, 0.01, 10);
Cube70.SetColor(0, 0.4804, 0.1413);
Cube70.group = 7;
models.emplace_back(Cube70);

Model Torus71;
Torus71.CreateTours(0.217, 0.8, 10, 10);
Torus71.Translate(-2, 0.24, 0.341);
Torus71.Scale(0.41, 0.41, 0.41);
Torus71.Rotate(0, 89.65, 0);
Torus71.SetColor(0.543, 0.8398, 0.8398);
Torus71.group = 8;
models.emplace_back(Torus71);

Model Torus72;
Torus72.CreateTours(0.217, 0.8, 10, 10);
Torus72.Translate(2, 0.364, -0.822);
Torus72.Scale(0.41, 0.41, 0.41);
Torus72.Rotate(0, 89.65, 0);
Torus72.SetColor(0.543, 0.8398, 0.8398);
Torus72.group = 8;
models.emplace_back(Torus72);

Model Torus73;
Torus73.CreateTours(0.217, 0.8, 10, 10);
Torus73.Translate(2, 0.364, 0.806);
Torus73.Scale(0.41, 0.41, 0.41);
Torus73.Rotate(0, 89.65, 0);
Torus73.SetColor(0.543, 0.8398, 0.8398);
Torus73.group = 8;
models.emplace_back(Torus73);

Model Torus74;
Torus74.CreateTours(0.217, 0.8, 10, 10);
Torus74.Translate(2, 0.364, 2);
Torus74.Scale(0.41, 0.41, 0.41);
Torus74.Rotate(0, 89.65, 0);
Torus74.SetColor(0.543, 0.8398, 0.8398);
Torus74.group = 8;
models.emplace_back(Torus74);

Model Cube75;
Cube75.CreateCube(0.5);
Cube75.Translate(-2, -0.352, 0.171);
Cube75.Scale(10, 1.126, 0.435);
Cube75.Rotate(0, 89.65, 0);
Cube75.SetColor(0.543, 0.8398, 0.8398);
Cube75.group = 8;
models.emplace_back(Cube75);

Model Sphere76;
Sphere76.CreateSphere(0.5, 10, 10);
Sphere76.Translate(2, 0.131, 1.385);
Sphere76.Scale(0.393, 0.393, 0.393);
Sphere76.SetColor(0.543, 0.8398, 0.8398);
Sphere76.group = 8;
models.emplace_back(Sphere76);

Model Cube77;
Cube77.CreateCube(0.5);
Cube77.Translate(2, -0.352, 0.171);
Cube77.Scale(10, 1.126, 0.435);
Cube77.Rotate(0, 89.65, 0);
Cube77.SetColor(0.543, 0.8398, 0.8398);
Cube77.group = 8;
models.emplace_back(Cube77);

Model CollisionBox78;
CollisionBox78.CreateWireCube(0.5);
CollisionBox78.Translate(2, -0.341, 0.182);
CollisionBox78.Scale(0.719, 1.356, 10);
CollisionBox78.SetColor(0.543, 0.8398, 0.8398);
CollisionBox78.collider = true;
CollisionBox78.group = 8;
models.emplace_back(CollisionBox78);

Model CollisionBox79;
CollisionBox79.CreateWireCube(0.5);
CollisionBox79.Translate(-2, -0.397, 0.294);
CollisionBox79.Scale(0.719, 1.498, 10);
CollisionBox79.SetColor(0.543, 0.8398, 0.8398);
CollisionBox79.collider = true;
CollisionBox79.group = 8;
models.emplace_back(CollisionBox79);

Model Cube80;
Cube80.CreateCube(0.5);
Cube80.Translate(0.085, -0.369, -2);
Cube80.Scale(10, 1.126, 0.435);
Cube80.SetColor(0.543, 0.8398, 0.8398);
Cube80.group = 8;
models.emplace_back(Cube80);

Model Torus81;
Torus81.CreateTours(0.217, 0.8, 10, 10);
Torus81.Translate(-2, 0.24, -1.07);
Torus81.Scale(0.41, 0.41, 0.41);
Torus81.Rotate(0, 89.65, 0);
Torus81.SetColor(0.543, 0.8398, 0.8398);
Torus81.group = 8;
models.emplace_back(Torus81);

Model Torus82;
Torus82.CreateTours(0.217, 0.8, 10, 10);
Torus82.Translate(0, 0.227, -2);
Torus82.Scale(0.41, 0.41, 0.41);
Torus82.SetColor(0.543, 0.8398, 0.8398);
Torus82.group = 8;
models.emplace_back(Torus82);

Model Torus83;
Torus83.CreateTours(0.217, 0.8, 10, 10);
Torus83.Translate(1.319, 0.227, -2);
Torus83.Scale(0.41, 0.41, 0.41);
Torus83.SetColor(0.543, 0.8398, 0.8398);
Torus83.group = 8;
models.emplace_back(Torus83);

Model Sphere84;
Sphere84.CreateSphere(0.5, 10, 10);
Sphere84.Translate(-1.121, 0.213, -2);
Sphere84.Scale(0.393, 0.393, 0.393);
Sphere84.SetColor(0.543, 0.8398, 0.8398);
Sphere84.group = 8;
models.emplace_back(Sphere84);

Model Sphere85;
Sphere85.CreateSphere(0.5, 10, 10);
Sphere85.Translate(2, 0.099, -1.636);
Sphere85.Scale(0.393, 0.393, 0.393);
Sphere85.SetColor(0.543, 0.8398, 0.8398);
Sphere85.group = 8;
models.emplace_back(Sphere85);

Model Sphere86;
Sphere86.CreateSphere(0.5, 10, 10);
Sphere86.Translate(2, 0.131, -0.126);
Sphere86.Scale(0.393, 0.393, 0.393);
Sphere86.SetColor(0.543, 0.8398, 0.8398);
Sphere86.group = 8;
models.emplace_back(Sphere86);

Model Sphere87;
Sphere87.CreateSphere(0.5, 10, 10);
Sphere87.Translate(0.014, 0.213, -2);
Sphere87.Scale(0.393, 0.393, 0.393);
Sphere87.SetColor(0.543, 0.8398, 0.8398);
Sphere87.group = 8;
models.emplace_back(Sphere87);

Model Sphere88;
Sphere88.CreateSphere(0.5, 10, 10);
Sphere88.Translate(1.319, 0.213, -2);
Sphere88.Scale(0.393, 0.393, 0.393);
Sphere88.SetColor(0.543, 0.8398, 0.8398);
Sphere88.group = 8;
models.emplace_back(Sphere88);

Model Torus89;
Torus89.CreateTours(0.217, 0.8, 10, 10);
Torus89.Translate(-1.128, 0.227, -2);
Torus89.Scale(0.41, 0.41, 0.41);
Torus89.SetColor(0.543, 0.8398, 0.8398);
Torus89.group = 8;
models.emplace_back(Torus89);

Model CollisionBox90;
CollisionBox90.CreateWireCube(0.5);
CollisionBox90.Translate(0, 0.014, -1.972);
CollisionBox90.Scale(9.504, 1, 1);
CollisionBox90.SetColor(0.543, 0.8398, 0.8398);
CollisionBox90.collider = true;
CollisionBox90.group = 8;
models.emplace_back(CollisionBox90);

Model Torus91;
Torus91.CreateTours(0.217, 0.8, 10, 10);
Torus91.Translate(-2, 0.224, 1.628);
Torus91.Scale(0.41, 0.41, 0.41);
Torus91.Rotate(0, 89.65, 0);
Torus91.SetColor(0.543, 0.8398, 0.8398);
Torus91.group = 8;
models.emplace_back(Torus91);

Model Sphere92;
Sphere92.CreateSphere(0.5, 10, 10);
Sphere92.Translate(-2, 0.131, 0.965);
Sphere92.Scale(0.393, 0.393, 0.393);
Sphere92.SetColor(0.543, 0.8398, 0.8398);
Sphere92.group = 8;
models.emplace_back(Sphere92);

Model Sphere93;
Sphere93.CreateSphere(0.5, 10, 10);
Sphere93.Translate(-2, 0.131, -0.419);
Sphere93.Scale(0.393, 0.393, 0.393);
Sphere93.SetColor(0.543, 0.8398, 0.8398);
Sphere93.group = 8;
models.emplace_back(Sphere93);

Model CollisionBox94;
CollisionBox94.CreateWireCube(0.5);
CollisionBox94.Translate(0.964, -0.256, 1.175);
CollisionBox94.Scale(2.206, 1.569, 1.337);
CollisionBox94.collider = true;
CollisionBox94.group = 9;
models.emplace_back(CollisionBox94);

Model Cube95;
Cube95.CreateCube(0.5);
Cube95.Translate(1.006, -0.327, 1.104);
Cube95.Scale(2.136, 1.285, 1.337);
Cube95.SetColor(0.9069, 0.9069, 0.9069);
Cube95.group = 9;
models.emplace_back(Cube95);

Model Torus96;
Torus96.CreateTours(0.1, 0.8, 10, 10);
Torus96.Translate(1.262, -0.214, 1.356);
Torus96.Scale(0.357, 0.357, 0.357);
Torus96.Rotate(0, 89.36, 0);
Torus96.SetColor(0.1267, 0.03542, 0.6569);
Torus96.group = 9;
models.emplace_back(Torus96);

Model Torus97;
Torus97.CreateTours(0.1, 0.8, 10, 10);
Torus97.Translate(0.921, -0.185, 1.44);
Torus97.Scale(0.357, 0.357, 0.357);
Torus97.Rotate(0, 89.36, 0);
Torus97.SetColor(0.06185, 0.06185, 0.4853);
Torus97.group = 9;
models.emplace_back(Torus97);

Model Cube98;
Cube98.CreateCube(0.5);
Cube98.Translate(1.106, 0, 1.524);
Cube98.Scale(0.789, 0.081, 0.15);
Cube98.SetColor(0, 0.08931, 1);
Cube98.group = 9;
models.emplace_back(Cube98);

Model Cube99;
Cube99.CreateCube(0.5);
Cube99.Translate(1.106, -0.469, 1.524);
Cube99.Scale(0.719, 0.081, 0.15);
Cube99.SetColor(0, 0.08931, 1);
Cube99.group = 9;
models.emplace_back(Cube99);

Model Cube100;
Cube100.CreateCube(0.5);
Cube100.Translate(1.078, -0.114, 1.65);
Cube100.Scale(0.719, 0.01, 0.15);
Cube100.SetColor(0, 0.08931, 1);
Cube100.group = 9;
models.emplace_back(Cube100);

Model Cube101;
Cube101.CreateCube(0.5);
Cube101.Translate(1.006, -0.072, 1.104);
Cube101.Scale(1.923, 0.86, 0.988);
Cube101.SetColor(0, 0.543, 0.598);
Cube101.group = 9;
models.emplace_back(Cube101);

}
